# Generated by Django 2.2.9 on 2019-12-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialnumber', '0002_auto_20181023_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='perform_resource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
