# Generated by Django 2.2.9 on 2020-02-01 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serialnumber', '0003_serialnumber_perform_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serialnumber',
            options={'ordering': ['-last_modified_date']},
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='current_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wips', to='operation.Operation'),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialnumbers', to='workorder.WorkOrder'),
        ),
    ]
