# docker-compose.yml

version: '3'

services:

  

  wmp-redis:
    container_name: wmp-redis
    image: redis:5.0.6-alpine
    networks:
      - main
    volumes:
      - cache_data:/data
    ports:
      - 6379:6379

  cache-server:
    build:
      context: ./cache
    command: python cache.py
    container_name: cache-server
    depends_on:
      - wmp-redis
    networks:
      - main
    # environment:
    #   - REDIS_URL=redis://wmp-redis:6379/0
    ports:
      - 8001:5000

  wmp-server:
    container_name: wmp-server
    restart: always
    build: ./wmp
    depends_on:
      - cache-server
    expose:
      - "8000"
    links:
      - postgres:postgres
      # - redis:redis
    networks:
      - main
    volumes:
      - web-django:/usr/src/app
      - web-static:/staticfiles
    env_file: .env
    environment:
      - CACHE_SERVER_URL=http://cache-server:8001
      # DEBUG: 'False'
    command: gunicorn wmp.wsgi:application -w 2 -b :8000
    ports:
      - 8000:8000

# gunicorn --workers=3 wmp.wsgi -b 0.0.0.0:8000

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres-server
    ports:
      - "5433:5432"
    networks:
      - main
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:  
  cache_data:
  web-django:
  web-static:
  pgdata:
  cache-server:

networks:
  main:
