# Generated by Django 2.0.4 on 2019-12-14 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='customer_pn',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='customer_rev',
        ),
        migrations.AddField(
            model_name='bom',
            name='fg_pn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Finish Goods Part Number'),
        ),
        migrations.AddField(
            model_name='bom',
            name='fg_rev',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Finish Goods Revision'),
        ),
        migrations.AddField(
            model_name='bom_detail',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bom',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
    ]
