# Generated by Django 2.2.9 on 2019-12-21 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_auto_20191214_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='pn',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Part number does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='bom_detail',
            name='pn',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Part number does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='bom_detail',
            name='rd',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='RD does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Ref Destinator'),
        ),
    ]
