# Generated by Django 2.2.9 on 2020-02-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_auto_20191221_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom_detail',
            name='pn_type',
            field=models.CharField(choices=[('COMPONENT', 'Component'), ('MODULE', 'Module with serial number'), ('BUILD', 'Inernal Build with serial number')], default='COMPONENT', max_length=10, verbose_name='Part Type'),
        ),
    ]
