# Generated by Django 2.2.9 on 2020-02-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_auto_20200201_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom_detail',
            name='package',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bom_detail',
            name='package_family',
            field=models.CharField(choices=[('IP', 'Through-hole'), ('SFM', 'Surface mount'), ('CC', 'Chip carrier'), ('PGA', 'Pin grid arrays'), ('FP', 'Flat packages'), ('SOP', 'Small outline packages'), ('CSP', 'Chip-scale packages'), ('BGA', 'Ball grid array'), ('OTHER', 'Transistor, diode, small-pin-count IC packages')], default='SFM', max_length=10),
        ),
        migrations.AddField(
            model_name='bom_detail',
            name='pin',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bom_detail',
            name='thickness',
            field=models.DecimalField(decimal_places=2, default=0.18, max_digits=5),
        ),
    ]
