# Generated by Django 2.0.4 on 2019-12-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingdetailacceptset',
            name='routingdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepts', to='routing.RoutingDetail'),
        ),
        migrations.AlterField(
            model_name='routingdetailparameterset',
            name='routingdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='routing.RoutingDetail'),
        ),
        migrations.AlterField(
            model_name='routingdetailrejectset',
            name='routingdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejects', to='routing.RoutingDetail'),
        ),
    ]
