# Generated by Django 2.2.9 on 2019-12-21 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20191221_0841'),
        ('routing', '0002_auto_20191214_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routing',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='routingdetailaccept',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='routingdetailhook',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='routingdetailnext',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='routingdetailreject',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='routingdetail',
            unique_together={('routing', 'operation')},
        ),
    ]
