# Generated by Django 2.0.4 on 2019-12-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
