# Generated by Django 2.2.9 on 2020-02-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_auto_20191221_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='build_type',
            field=models.CharField(choices=[('BUILD_TO_ORDER', 'Build to Order'), ('BUILD_TO_STOCK', 'Build to Stock'), ('BUILD_TO_BUILD', 'Build to Build')], default='BUILD_TO_ORDER', max_length=20),
        ),
    ]
