# Generated by Django 2.2.9 on 2019-12-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performing', '0002_auto_20191221_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performing',
            old_name='loop',
            new_name='interval',
        ),
    ]
