# Generated by Django 2.2.9 on 2020-02-01 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performing', '0003_auto_20191221_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performing',
            options={'ordering': ['-stop_time']},
        ),
        migrations.AlterField(
            model_name='performing',
            name='sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performings', to='serialnumber.SerialNumber'),
        ),
    ]
