# Generated by Django 2.2.9 on 2019-12-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20180718_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
