# Generated by Django 2.2.9 on 2020-02-01 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='itemlist',
            unique_together={('name', 'item')},
        ),
    ]
