# Generated by Django 2.2.9 on 2020-02-22 07:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routing', '0004_routingdetailoperationchoice'),
        ('symptom', '0008_auto_20181218_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Is Fixed'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomcode',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptomcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptoms', to='symptom.SymptomCode'),
        ),
        migrations.AlterField(
            model_name='symptomcode',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.CreateModel(
            name='SymptomCode_Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.IntegerField(default=1)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('category1', models.CharField(blank=True, max_length=50, null=True)),
                ('category2', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('routingdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptomcode_usages', to='routing.RoutingDetail')),
                ('symptomcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptomcode_usages', to='symptom.SymptomCode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
