# Generated by Django 2.0.4 on 2019-12-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_pn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_rev',
        ),
        migrations.AddField(
            model_name='product',
            name='fg_pn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Finish Goods Part number'),
        ),
        migrations.AddField(
            model_name='product',
            name='fg_rev',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Finish Goods Revision number'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Part number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rev',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Revision number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.Routing', verbose_name='Routing Name'),
        ),
    ]
