# Generated by Django 2.2.9 on 2020-02-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_assembly_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_usage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
