# Generated by Django 2.2.9 on 2020-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_assembly_usage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_detail',
            name='datecode_regexp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Datecode RegExp Validation'),
        ),
        migrations.AddField(
            model_name='assembly_detail',
            name='lotcode_regexp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lotcode RegExp Validation'),
        ),
        migrations.AddField(
            model_name='assembly_detail',
            name='sn_regexp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial number RegExp Validation'),
        ),
        migrations.AddField(
            model_name='assembly_detail',
            name='supplycode_regexp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplycode RegExp Validation'),
        ),
    ]
