# Generated by Django 2.2.9 on 2020-02-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_auto_20200203_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_detail',
            name='msd_control',
            field=models.BooleanField(default=False, verbose_name='Enable MSD Control'),
        ),
    ]
