# Generated by Django 2.2.9 on 2019-12-21 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('ASSEMBLY', 'Assembly'), ('REGISTRATION', 'Registration'), ('INSPECTION', 'Inspection'), ('TROUBLESHOOTING', 'Troubleshooting'), ('REPAIR', 'Repairation'), ('SHIPMENT', 'Shipment'), ('PACKING', 'Packing'), ('END', 'Ending Process')], default='INSPECTION', max_length=20),
        ),
    ]
