# Generated by Django 2.2.9 on 2020-02-07 23:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0002_auto_20191221_0841'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serialnumber', '0004_auto_20200201_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Number does not allow special charecters', regex='^[\\w-]+$')])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('category1', models.CharField(blank=True, max_length=50, null=True)),
                ('category2', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('pn', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Part number does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Part number')),
                ('rev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Part Revision')),
                ('datecode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date code')),
                ('lotcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot code')),
                ('supcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier code')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=1)),
                ('pn_type', models.CharField(choices=[('COMPONENT', 'Component'), ('MODULE', 'Module with serial number'), ('BUILD', 'Inernal Build with serial number')], default='MODULE', max_length=10, verbose_name='Part Type')),
                ('last_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_last_operations', to='operation.Operation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='serialnumber.SerialNumber', verbose_name='Assembled on')),
                ('reserved_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservedfors', to='serialnumber.SerialNumber', verbose_name='Reserved for')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified_date'],
                'unique_together': {('number', 'pn')},
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('number', models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Number does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Batch number')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode label')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('category1', models.CharField(blank=True, max_length=50, null=True)),
                ('category2', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('pn', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Part number does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Part number')),
                ('rev', models.CharField(blank=True, max_length=100, null=True, verbose_name='Part Revision')),
                ('datecode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date code')),
                ('lotcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot code')),
                ('supcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier code')),
                ('qty', models.IntegerField(default=0, verbose_name='Total Qty')),
                ('carrier', models.CharField(choices=[('TRAY', 'Tray'), ('TUBE', 'Tube'), ('TAPE', 'Tape'), ('REEL', 'Reel'), ('OTHER', 'Other')], default='REEL', max_length=10)),
                ('msl', models.CharField(choices=[('1', '1'), ('2', '2'), ('2A', '2a'), ('3', '3'), ('4', '4'), ('5', '5'), ('5A', '5a'), ('6', '6')], default='2', max_length=3, verbose_name='Moisture Sensitivity Levels')),
                ('floor_life', models.IntegerField(default=72, verbose_name='Floor life (hr)')),
                ('shelf_life', models.IntegerField(default=365, verbose_name='Shelf life (day)')),
                ('met', models.IntegerField(default=1, verbose_name='Manufacturer Exposure Time (hr)')),
                ('exp_date', models.DateTimeField(blank=True, null=True, verbose_name='Expire Date')),
                ('baking_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Baking Datetime')),
                ('baking_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Finish Baking Datetime')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified_date'],
            },
        ),
        migrations.CreateModel(
            name='Assembled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_type', models.CharField(choices=[('COMPONENT', 'Component'), ('MODULE', 'Module with serial number'), ('BUILD', 'Inernal Build with serial number')], default='MODULE', max_length=10, verbose_name='Part Type')),
                ('refdes', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='RD does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Ref Destinator')),
                ('pn', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Part number does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Part Number')),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('action_date', models.DateTimeField(auto_now=True, null=True)),
                ('action_status', models.BooleanField(choices=[(True, 'Assembly'), (False, 'De-Assembly')], default=True)),
                ('component_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled', to='component.Component', verbose_name='Part Number')),
                ('module_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled', to='component.Module', verbose_name='Module Number')),
                ('number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled', to='serialnumber.SerialNumber', verbose_name='Unit serial number')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled', to='operation.Operation', verbose_name='Assembled Operation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
