# Generated by Django 2.2.9 on 2020-02-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='category1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='category2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
