# Generated by Django 2.2.9 on 2020-02-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembled',
            name='rev',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Part Revision'),
        ),
    ]
