# Generated by Django 2.2.9 on 2020-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_auto_20200205_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='last_operation',
        ),
        migrations.AddField(
            model_name='part',
            name='category1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='category2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
