# Generated by Django 2.2.9 on 2020-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_assembled_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembled',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
